const towns = [
  'Ansonia', 'Ashford', 'Avon', 'Berlin', 'Bethany', 'Bethel', 'Bethlehem',
  'Bloomfield', 'Branford', 'Bristol', 'Brookfield', 'Canaan', 'Canton',
  'Cheshire', 'Chester', 'Colchester', 'Columbia', 'Cornwall', 'Coventry',
  'Cromwell', 'Danbury', 'Derby', 'Eastford', 'East Haddam', 'East Haven',
  'Farmington', 'Chaplin', 'Clinton', 'East Lyme', 'Easton', 'Enfield', 'Essex',
  'Durham', 'Franklin', 'Glastonbury', 'Hamden', 'Granby', 'Greenwich',
  'Colebrook', 'East Windsor', 'Griswold', 'Bolton', 'Groton', 'Guilford',
  'Hartford', 'Harwinton', 'Milford', 'Killingly', 'Killingworth', 'Lebanon',
  'Lisbon', 'Litchfield', 'Lyme', 'Manchester', 'Putnam', 'Norwalk', 'Stafford',
  'Mansfield', 'Sherman', 'Meriden', 'Stratford', 'Roxbury', 'Oxford', 'Old Lyme',
  'Norwich', 'Sharon', 'Monroe', 'Tolland', 'Torrington', 'Naugatuck',
  'Ridgefield', 'New London', 'New Britain', 'Orange', 'New Canaan',
  'New Fairfield', 'New Hartford', 'New Haven', 'Somers', 'Newtown',
  'North Haven', 'West Haven', 'Morris', 'Thompson', 'Stonington', 'Stamford',
  'Newington', 'Plainfield', 'Vernon', 'Plainville', 'Watertown',
  'West Hartford', 'Plymouth', 'Portland', 'Redding', 'Warren', 'Rocky Hill',
  'Salem', 'Winchester', 'Shelton', 'Simsbury', 'Windsor', 'Southbury',
  'South Windsor', 'Brooklyn', 'Sterling', 'Ellington', 'Suffield', 'Thomaston',
  'East Hartford', 'Trumbull', 'Fairfield', 'Ledyard', 'Washington', 'Waterbury',
  'Hebron', 'Barkhamsted', 'Waterford', 'Westbrook', 'Wethersfield', 'Darien',
  'Willington', 'Wilton', 'Windsor Locks', 'Wolcott', 'Woodbury', 'Woodstock',
  'East Granby', 'Burlington', 'Bozrah', 'Goshen', 'Madison', 'Bridgeport',
  'Bridgewater', 'Kent', 'Beacon Falls', 'Andover', 'Hampton', 'Montville',
  'Prospect', 'Deep River', 'Southington', 'Norfolk', 'Westport', 'Windham',
  'Wallingford', 'Weston', 'Voluntown', 'Middletown', 'Middlefield',
  'Middlebury', 'Old Saybrook', 'North Canaan', 'Preston', 'Scotland', 'Sprague',
  'Pomfret', 'Seymour', 'Woodbridge', 'Union', 'Haddam', 'Canterbury',
  'Marlborough', 'New Milford', 'North Stonington', 'East Hampton', 'Hartland',
  'Salisbury', 'North Branford'
]

export default towns;